# Generated by Django 3.1.6 on 2021-06-23 12:42

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateField(verbose_name='Start Date')),
                ('end_at', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('otm_or_place_of_education', models.CharField(max_length=300, verbose_name='Institution/Place of Education')),
                ('faculty_or_subject', models.CharField(max_length=300, verbose_name='Faculty/Subject')),
                ('learned_skill', models.TextField(verbose_name='Learned Skills')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200, verbose_name='Company Name')),
                ('occpation', models.TextField(max_length=300, verbose_name='Occupation')),
                ('qualification', models.TextField(verbose_name='Qualification')),
                ('start_at', models.DateField(verbose_name='Start Date')),
                ('end_at', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Company Web Site Link')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Company Phone-Number')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio-image/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=300, null=True, verbose_name='Caption')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Image',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio-cover-image/', verbose_name='Cover Image')),
                ('name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Name')),
                ('short_desc', models.TextField(blank=True, null=True, verbose_name='Short Description')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Project Link')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.CreateModel(
            name='PortfolioDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Portfolio Detail',
                'verbose_name_plural': 'Portfolio Details',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='student-image/', verbose_name='Your Image')),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='bg-image/', verbose_name='Background Image')),
                ('career', models.CharField(max_length=500, verbose_name='Career')),
                ('about_me', models.TextField(verbose_name='About Me')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
            },
        ),
    ]
