# Generated by Django 3.1.6 on 2021-06-23 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_resume', to='users.student'),
        ),
        migrations.AddField(
            model_name='portfoliodetail',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_detail', to='portfolio.portfolio'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_portfolio', to='users.student'),
        ),
        migrations.AddField(
            model_name='image',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_image', to='portfolio.portfoliodetail'),
        ),
        migrations.AddField(
            model_name='experience',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_experience', to='users.student'),
        ),
        migrations.AddField(
            model_name='education',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_education', to='users.student'),
        ),
    ]
